PROXMOX_IP_HOST = '192.168.0.2'
PROXMOX_HTTP_HOST = f'https://{PROXMOX_IP_HOST}:8006/api2/json'

PROXMOX_USERNAME_AT = 'user@pam'
PROXMOX_PASSWORD = 'password'
PROXMOX_USERNAME = 'user'

XEN_HOST = 'https://192.168.0.3:443'
XEN_USERNAME = 'user'
XEN_PASSWORD = 'password'
