# Generated by Django 5.0.6 on 2024-06-20 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Proxmox', 'Proxmox'), ('Xen', 'Xen'), ('Qemu', 'Qemu')], max_length=10)),
                ('host', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('http_host', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Web',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('Proxmox', 'Proxmox'), ('Xen', 'Xen'), ('Qemu', 'Qemu')], max_length=10)),
                ('address', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Vm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cores', models.IntegerField()),
                ('memory', models.IntegerField()),
                ('vmid', models.IntegerField()),
                ('disk_size', models.IntegerField()),
                ('storage', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('last_error', models.CharField(blank=True, max_length=100, null=True)),
                ('ip', models.CharField(blank=True, max_length=100, null=True)),
                ('port_spice', models.IntegerField(blank=True, null=True)),
                ('params', models.CharField(blank=True, max_length=100, null=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.connection')),
            ],
        ),
    ]
