# Generated by Django 5.0.6 on 2024-06-23 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vm',
            name='vmid',
        ),
    ]
