# Generated by Django 5.0.6 on 2024-06-25 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_remove_vm_vmid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='vm',
            name='disk_size',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='vm',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='vm',
            name='memory',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='web',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
